# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
variables:
 
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'sh-tutapp-svc'
  
  # Web app name
  webAppName: 'sh-tutapp'
  
  # Resource group
  resourceGroupName: 'tut-RG'
 
  # Environment name
  environmentName: 'sh-tutapp'
 
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Archive
  displayName: Archive stage
  jobs:  
  - job: Archive
    displayName: Archive
    pool:
      vmImage: $(vmImageName)
    steps:   
    - task: AzureAppServiceSettings@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1"
            },            
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            }
          ]
    - task: CmdLine@2
      displayName: 'Installing @babel/node and @babel/cli globally...'
      inputs:
        script: 'npm install -g @babel/cli @babel/node'
    - task: CmdLine@2
      displayName: 'Installing yarn globally...'
      inputs:
        script: 'npm install --global yarn '
    - task: Npm@1
      displayName: 'Install Dependencies'
      inputs:
        command: 'install'
#    - task: Npm@1
#      displayName: 'Build Application'
#      inputs:
#        command: 'custom'
#        customCommand: 'run build'         
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
 
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
 
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Archive
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:   
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: Matt-Test-NodeJS-Deploy'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|10.14'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
 